# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    groups:
      # Group for development dependencies
      dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        dependency-type: 'development'

      # Group for production dependencies
      production-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
        dependency-type: 'production'

      # Group for major updates (separated for better control)
      major-updates:
        patterns:
          - '*'
        update-types:
          - 'major'

      # Specific group for testing tools
      test-tools:
        patterns:
          - 'cypress*'
          - 'jest*'
          - 'testing-library*'
          - '@testing-library/*'

      # Group for build and development tools
      build-tools:
        patterns:
          - 'typescript*'
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'next*'
          - 'react*'
          - '@next/*'
