minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@incubateur-ademe/nosgestesclimat'
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - puppeteer
  - sharp
  - unrs-resolver
