packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - core-js
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

minimumReleaseAge: 10080 # 7 days

minimumReleaseAgeExclude:
  - '@incubateur-ademe/nosgestesclimat'
  # We explicitely need a new feature introduced in 1.379.0. Those 3 lines can be remove safely on 10/06/2026
  # @TODO
  - 'posthog-js'
  - '@posthog/core'
  - '@posthog/types'
  - '@posthog/browser-common'

onlyBuiltDependencies:
  - '@incubateur-ademe/nosgestesclimat'
  - '@nosgestesclimat/core'
  - '@prisma/engines'
  - '@sentry/cli'
  - msw
  - prisma
