export const SIMULATOR_PATH = '/simulateur/bilan'
export const TUTORIAL_PATH = '/tutoriel'
export const MON_ESPACE_PATH = '/mon-espace'
export const FAQ_PATH = '/questions-frequentes'
export const POLL_START_PATH = '/infos/commencer'
export const POLL_EMAIL_STEP = '/infos/email'
export const POLL_POSTAL_CODE_STEP = '/infos/codepostal'
export const POLL_BIRTHDAY_STEP = '/infos/naissance'
export const END_PAGE_PATH = '/fin'
export const DOCUMENTATION_PATH = '/documentation'
export const CONNEXION_PATH = '/connexion'
export const INSCRIPTION_PATH = '/inscription'
export const MON_ESPACE_RESULTS_PATH = '/mon-espace'
export const MON_ESPACE_ACTIONS_PATH = '/mon-espace/actions'
export const MON_ESPACE_GROUPS_PATH = '/mon-espace/groupes'
export const MON_ESPACE_SETTINGS_PATH = '/mon-espace/parametres'
export const MON_ESPACE_RESULTS_DETAIL_PATH =
  '/mon-espace/resultats/:simulationId'
