name: 'Setup Playwright and App'
description: 'Sets up dependencies and installs Playwright'
inputs:
  browser:
    description: 'Browser to install'
    required: true
    default: 'chromium'
runs:
  using: 'composite'
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Install Playwright
      shell: bash
      working-directory: ./apps/e2e
      run: |
        if [ "${{ inputs.browser }}" = "webkit" ]; then
          pnpm playwright install webkit --with-deps
        else
          pnpm playwright install "${{ inputs.browser }}"
        fi
