name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-server-preprod:
    name: Deploy server to preprod
    runs-on: ubuntu-latest
    environment: Preprod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deploy to Scalingo
        uses: ./.github/actions/deploy-scalingo
        with:
          fgp-deploy-token: ${{ secrets.FGP_DEPLOY_TOKEN }}
          fgp-deploy-url: ${{ vars.FGP_DEPLOY_URL }}
          scalingo-app-name: ${{ vars.SCALINGO_SERVER_APP_NAME }}
          git-ref: main

  deploy-site-preprod:
    name: Deploy site to preprod
    needs: deploy-server-preprod
    runs-on: ubuntu-latest
    environment: Preprod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Deploy to Scalingo
        uses: ./.github/actions/deploy-scalingo
        with:
          fgp-deploy-token: ${{ secrets.FGP_DEPLOY_TOKEN }}
          fgp-deploy-url: ${{ vars.FGP_DEPLOY_URL }}
          scalingo-app-name: ${{ vars.SCALINGO_SITE_APP_NAME }}
          git-ref: main

  e2e-preprod:
    name: Tests on preprod
    needs: [deploy-site-preprod, deploy-server-preprod]
    uses: ./.github/workflows/site:e2e.yaml
    secrets:
      FGP_BREVO_KEY: ${{ secrets.FGP_BREVO_KEY }}
    with:
      site_url: 'https://preprod.nosgestesclimat.fr'
      mailbox: brevo
      email_domain: e2e.test

  deploy-server-prod:
    name: Deploy server to prod
    needs: e2e-preprod
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deploy to Scalingo
        uses: ./.github/actions/deploy-scalingo
        with:
          fgp-deploy-token: ${{ secrets.FGP_DEPLOY_TOKEN }}
          fgp-deploy-url: ${{ vars.FGP_DEPLOY_URL }}
          scalingo-app-name: ${{ vars.SCALINGO_SERVER_APP_NAME }}
          git-ref: main

  deploy-site-prod:
    name: Deploy site to prod
    needs: deploy-server-prod
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deploy to Scalingo
        uses: ./.github/actions/deploy-scalingo
        with:
          fgp-deploy-token: ${{ secrets.FGP_DEPLOY_TOKEN }}
          fgp-deploy-url: ${{ vars.FGP_DEPLOY_URL }}
          scalingo-app-name: ${{ vars.SCALINGO_SITE_APP_NAME }}
          git-ref: main
